apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: deepscheduler
  labels:
    type: minio
spec:
  storageClassName: minio-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ds-data-minio"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - oscar-system-product-name