apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: deepscheduler
  labels:
    app: minio
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - name: minio-port
    port: 9000
    targetPort: 9000
    nodePort: 30011
  - name: minio-ui
    port: 9001
    targetPort: 9001
    nodePort: 30012
