FROM oscarvicente/deepscheduler-tensorflow-cuda-base

#Copy all needed files
#COPY ./ ./

#Install the dependencies specified in requirements.txt
RUN pip3 install -r requirements.txt

#Modify entrypoint to launch yout script
#ENTRYPOINT [ "python3", "-u", "main.py"]