apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-writer
spec:
  selector:
    matchLabels:
      app: deepscheduler-manager-writer
  template:
    metadata:
      labels:
        app: deepscheduler-manager-writer
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: oscarvicente/wait-for-it
          command: ["./wait-for-it.sh", "rabbitmq.default.svc.cluster.local:5672"]
        - name: wait-for-mongo 
          image: oscarvicente/wait-for-it
          command: ["./wait-for-it.sh", "mongodb.default.svc.cluster.local:27017"]
      containers:
      - name: deepscheduler-manager-writer
        image: oscarvicente/deepscheduler-manager-writer
        env:
          - name: MONGO_HOST
            value: mongodb://mongodb.default.svc.cluster.local
          - name: RABBIT_HOST
            value: rabbitmq.default.svc.cluster.local
