apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: deepscheduler
spec:
  serviceName: rabbitmq
  volumeClaimTemplates: []
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-k8s
          image: rabbitmq:management
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amqp
              protocol: TCP
              containerPort: 5672
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 10 &&rabbitmqadmin declare queue name=request_queue durable=true && rabbitmqadmin declare exchange name=backend_exchange type=direct && rabbitmqadmin declare binding source=backend_exchange destination_type=queue destination=request_queue routing_key=request_queue"]

      #nodeSelector:
      #  gpu-node: "false"