apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: http
      port: 15672
      targetPort: 15672
      nodePort: 30000
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30001
#Using nodeport for testing purposes, we can change it with custerip
