apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  volumeClaimTemplates: []
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-k8s
          image: rabbitmq:management
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: ampq
              protocol: TCP
              containerPort: 5672
      nodeSelector:
        gpu-node: "false"