apiVersion: v1
kind: Service
metadata:
  name: deepscheduler-frontend
  namespace: deepscheduler
  labels:
    app: deepscheduler-frontend
spec:
  type: NodePort
  selector:
    app: deepscheduler-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30004
