apiVersion: v1
kind: Service
metadata:
  name: deepscheduler-reverse-proxy
  namespace: deepscheduler
  labels:
    app: deepscheduler-reverse-proxy
spec:
  type: NodePort
  selector:
    app: deepscheduler-reverse-proxy
  ports:
    - name: http
      port: 8889
      targetPort: 8889
      nodePort: 30010