apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepscheduler-backend
spec:
  selector:
    matchLabels:
      app: deepscheduler-backend
  template:
    metadata:
      labels:
        app: deepscheduler-backend
    spec:
      initContainers:
        - name: wait-for-mongo
          image: oscarvicente/wait-for-it
          command: ["./wait-for-it.sh", "mongodb.default.svc.cluster.local:27017"]
      containers:
      - name: deepscheduler-backend-k8s
        image: oscarvicente/deepscheduler-backend
        env: 
          - name: MONGO_HOST
            value: mongodb.default.svc.cluster.local/ds
          - name: GOOGLE_CLIENT_ID
            value: 189403674376-44r34q7r7o1cs5d3po57ql6fm483iu09.apps.googleusercontent.com
          - name: GOOGLE_SECRET
            value: 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
        ports:
        - name: http
          protocol: TCP
          containerPort: 3000
