apiVersion: v1
kind: Service
metadata:
  name: deepscheduler-backend
  namespace: deepscheduler
  labels:
    app: deepscheduler-backend
spec:
  type: NodePort
  selector:
    app: deepscheduler-backend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30003
  - name: websocket
    port: 3001
    targetPort: 3001
    nodePort: 30005
