apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    type: mongo
spec:
  storageClassName: mongo-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ds-data-mongo"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - oscar-system-product-name