apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
  labels:
    app: mongodb
spec:
  resources:
    requests:
      storage: 200Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: mongo-local-storage