apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-local-pv
  labels:
    type: local
spec:
  storageClassName: mongo-local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ds-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - oscar-system-product-name