version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network

  orchestrator:
    build: ../
    networks:
      - app-network
    command: ["./wait-for-it.sh", "rabbit:5672", "--", "python", "orchestrator.py"]
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
