apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: orchestrator
spec:
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: oscarvicente/wait-for-it
          command: ["./wait-for-it.sh", "rabbitmq.default.svc.cluster.local:5672"]
        - name: wait-for-mongo 
          image: oscarvicente/wait-for-it
          command: ["./wait-for-it.sh", "mongodb.default.svc.cluster.local:27017"]
      containers:
        - name: orchestrator
          image: oscarvicente/deepscheduler-orchestrator
          env:
            - name: RABBIT_HOST
              value: rabbitmq.default.svc.cluster.local
            - name: REQUEST_QUEUE
              value: request_queue
            - name: MINIO_CLIENT
              value: minio-oscarvx00.cloud.okteto.net
            - name: MINIO_ACCESS
              valueFrom:
                secretKeyRef:
                  name: orchestrator-secret
                  key: MINIO_ACCESS
              value: myaccesskey
            - name: MINIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: orchestrator-secret
                  key: MINIO_SECRET
            - name: MINIO_RESULTS_BUCKET
              value: users-results
            - name: MONGO_HOST
              value: mongodb.default.svc.cluster.local
          volumeMounts:
            - mountPath: "/var/run/docker.sock"
              name: dockersock
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
      nodeSelector:
        gpu-node: "true"
